# Generated by Django 4.2 on 2023-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
