# Generated by Django 4.2 on 2023-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_alter_movie_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
