# Generated by Django 4.2 on 2023-05-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0005_alter_movie_imdblink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbLink',
            new_name='imdblink',
        ),
    ]
