# Generated by Django 4.2 on 2023-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0007_alter_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
