# Generated by Django 4.2 on 2023-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0008_alter_movie_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
