# Generated by Django 4.2 on 2023-05-27 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userview", "0008_alter_movie_movieid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="timestamp",
        ),
    ]
