# Generated by Django 4.2 on 2023-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userview", "0009_remove_comments_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movieid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
