# Generated by Django 4.2 on 2023-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userview", "0010_alter_movie_movieid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movieid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
